name: API CI pipeline for development branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  api-ci-development:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./QuickNoteVault.API

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build