name: QuickNoteVault.API CI pipeline for development branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./QuickNoteVault.API.sln

      - name: Build
        run: dotnet build ./QuickNoteVault.API.sln --no-restore

      - name: Test
        run: dotnet test ./QuickNoteVault.API.sln --no-restore --no-build