name: Client CI pipeline for development branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  client-ci-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --dir ./QuickNoteVault.client

      - name: Dir
        run: |
          ls
          cd QuickNoteVault.client
          ls

      - name: Build
        run: pnpm build --dir ./QuickNoteVault.client