name: Client CI pipeline for development branch

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  client-ci-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check dir
        run: ls

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Check dir
        run: ls

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Check dir
        run: ls

      - name: Install dependencies
        run: pnpm install ./QuickNoteVault.client

      - name: Check dir
        run: ls

      - name: Change dir
        run: cd ./QuickNoteVault.client

      - name: Check dir 2
        run: ls

      - name: Build
        run: pnpm build ./QuickNoteVault.client